# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts 'once upon a time...'

puts 'let there be...'
User.create(username:'a',password: 'password')
User.create(username:'b',password: 'password')
User.create(username:'c',password: 'password')
User.create(username:'d',password: 'password')
User.create(username:'e',password: 'password')
User.create(username:'f',password: 'password')
User.create(username:'g',password: 'password')
User.create(username:'h',password: 'password')
User.create(username:'i',password: 'password')
User.create(username:'j',password: 'password')
puts 'users'

puts 'let there be...'
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:1,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:2,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:3,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:4,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:5,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:5,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:6,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:7,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:8,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:9,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")

Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'w',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
Post.create(user_id:10,result:'l',pick:'Jets ML',odds:'-110',caption:'I really like this pick. Take it with me and make some money, or fade it and lose. Your choice idrc either way. I need more spew here. blah blah blah blah balah blah blah blah. isreal is buns. what a fucking embarrassment losers. stinky loser bums.',start:"2022-09-08 17:36:51.543419000 +0000")
puts 'posts'

puts 'let there be...'
50.times do |i|
    Tail.create(user_id:1,post_id:rand(21..178))
    Fade.create(user_id:1,post_id:rand(21..178))
    Tail.create(user_id:10,post_id:rand(1..156))
    Fade.create(user_id:10,post_id:rand(1..156))
end

45.times do |i|
    Tail.create(user_id:2,post_id:rand(35..178))
    Fade.create(user_id:2,post_id:rand(35..178))
    Tail.create(user_id:9,post_id:rand(1..143))
    Fade.create(user_id:9,post_id:rand(1..143))
end

40.times do |i|
    Tail.create(user_id:3,post_id:rand(49..178))
    Fade.create(user_id:3,post_id:rand(49..178))
    Tail.create(user_id:8,post_id:rand(1..122))
    Fade.create(user_id:8,post_id:rand(1..122))
end

35.times do |i|
    Tail.create(user_id:4,post_id:rand(69..178))
    Fade.create(user_id:4,post_id:rand(69..178))
    Tail.create(user_id:7,post_id:rand(1..101))
    Fade.create(user_id:7,post_id:rand(1..101))
end

30.times do |i|
    Tail.create(user_id:5,post_id:rand(81..178))
    Fade.create(user_id:5,post_id:rand(81..178))
    Tail.create(user_id:6,post_id:rand(1..80))
    Fade.create(user_id:6,post_id:rand(1..80))
end

20.times do |i|
    Tail.create(user_id:5,post_id:rand(1..68))
    Fade.create(user_id:5,post_id:rand(1..68))
    Tail.create(user_id:6,post_id:rand(102..178))
    Fade.create(user_id:6,post_id:rand(102..178))
end

15.times do |i|
    Tail.create(user_id:4,post_id:rand(1..48))
    Fade.create(user_id:4,post_id:rand(1..48))
    Tail.create(user_id:7,post_id:rand(123..178))
    Fade.create(user_id:7,post_id:rand(123..178))
end

10.times do |i|
    Tail.create(user_id:3,post_id:rand(1..34))
    Fade.create(user_id:3,post_id:rand(1..34))
    Tail.create(user_id:8,post_id:rand(144..178))
    Fade.create(user_id:8,post_id:rand(144..178))
end

5.times do |i|
    Tail.create(user_id:2,post_id:rand(1..33))
    Fade.create(user_id:2,post_id:rand(1..33))
    Tail.create(user_id:9,post_id:rand(157..178))
    Fade.create(user_id:9,post_id:rand(157..178))
end
puts 'tails and fades'

User.find_each(&:save)
puts 'made the user calculations'

Post.find_each(&:save)
puts 'made the post calculations'

puts 'The End.'